# Development overrides
# This file is automatically loaded by docker-compose
# Use: docker-compose up (automatically includes this file)

services:
  healthcare_ai:
    build:
      target: development
    volumes:
      - .:/app
      - /app/.venv  # Exclude venv from bind mount
    environment:
      DEBUG: "true"
      LOG_LEVEL: DEBUG
      RELOAD: "true"
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    build:
      target: development
    volumes:
      - .:/app
      - /app/.venv
    environment:
      DEBUG: "true"
      LOG_LEVEL: DEBUG
